sudo: required
services:
  - docker

before_install:
  - docker build -t axcientsawhney/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true axcientsawhney/react-test npm test -- --coverage

after_success:
  - docker build -t axcientsawhney/multi-client ./client
  - docker build -t axcientsawhney/multi-nginx ./nginx
  - docker build -t axcientsawhney/multi-server ./server
  - docker build -t axcientsawhney/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push axcientsawhney/multi-client
  - docker push axcientsawhney/multi-nginx
  - docker push axcientsawhney/multi-server
  - docker push axcientsawhney/multi-worker
